site_name: AmagZ的小站
site_url: https://AmagZ.github.io/  # 网站最终部署的URL
site_author: AmagZ  # 作者信息

nav:
    - Home: index.md
    - Music: 
        - Overview: musicreview/index.md
        - AmagZ的韦瓦第计划:
            - 春日入侵企划: musicreview/Vivaldi/spring-playlist.md
        - 苏打绿:
            - 夏/狂热: musicreview/Sodagreen/summer.md
            - 冬 未了: musicreview/Sodagreen/winter.md
        - 陈绮贞: 
            - 吉他手 Groupies: musicreview/Chen Qizhen/Groupies.md
        - Radiohead:
            - In Rainbows: musicreview/Radiohead/inrainbows.md
            - OK Computer: musicreview/Radiohead/okc.md
        - 陶喆:
            - musicreview/DT/index.md
                - David Tao 同名专辑: musicreview/DT/David Tao.md
                - 黑色柳丁: musicreview/DT/heiseliuding.md
        - 周杰伦:
            - 我的周杰伦 Top20: musicreview/Jay/Jaytop20.md
            - Jay 同名专辑: musicreview/Jay/jay.md
            - 太阳之子: musicreview/Jay/taiyangzhizi.md
        - 万能青年旅店:
            - 万能青年旅店 同名专辑: musicreview/Wanqing/wnqnld.md
    - Photograph: photo.md
    - Econ: econ.md

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top

  palette:
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/custom.css



copyright: Copyright &copy; 2025 AmagZ 
