site_name: AmagZ的小站
site_url: https://AmagZ.github.io/  # 网站最终部署的URL
site_author: AmagZ  # 作者信息

nav:
    - Home: index.md
    - Music: 
        - Overview: musicreview/index.md
        - 韦瓦第计划:
            - 春日入侵企划: musicreview/Vivaldi/spring-playlist.md
        - 陶喆:
            - 黑色柳丁: musicreview/DT/heiseliuding.md
    - Photograph: photo.md
    - Econ: econ.md

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top

  palette:
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/custom.css



copyright: Copyright &copy; 2025 AmagZ 
